interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: USB_MSC_CLIENT.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x220a4
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x80001c1: __do_global_dtors_aux
  0x80001e5: frame_dummy
  0x8000201: memchr
  0x80002a1: __aeabi_uldivmod
  0x80002d1: __udivmoddi4
  0x8000595: __aeabi_idiv0
  0x8000599: main
  0x80005f5: SystemClock_Config
  0x80006b9: PeriphCommonClock_Config
  0x8000719: MX_ADC1_Init
  0x80007e1: MX_DFSDM1_Init
  0x8000851: MX_I2C1_Init
  0x80008d1: MX_I2C2_Init
  0x8000951: MX_OCTOSPI1_Init
  0x80009fd: MX_SPI1_Init
  0x8000a79: MX_SPI3_Init
  0x8000af5: MX_USART1_UART_Init
  0x8000b8d: MX_USART2_UART_Init
  0x8000c29: MX_USART3_UART_Init
  0x8000cc1: MX_GPIO_Init
  0x8000f25: Error_Handler
  0x8000f31: RetargetInit
  0x8000f61: _write
  0x8000fb9: _read
  0x8001009: HAL_MspInit
  0x8001051: HAL_ADC_MspInit
  0x80010d1: HAL_DFSDM_ChannelMspInit
  0x8001199: HAL_I2C_MspInit
  0x80012dd: HAL_OSPI_MspInit
  0x80013b5: HAL_SPI_MspInit
  0x80014a1: HAL_UART_MspInit
  0x800166d: NMI_Handler
  0x8001673: HardFault_Handler
  0x800167b: MemManage_Handler
  0x8001683: BusFault_Handler
  0x800168b: UsageFault_Handler
  0x8001691: SVC_Handler
  0x800169f: DebugMon_Handler
  0x80016ad: PendSV_Handler
  0x80016bb: SysTick_Handler
  0x80016c7: EXTI9_5_IRQHandler
  0x80016e9: EXTI15_10_IRQHandler
  0x8001721: OTG_FS_IRQHandler
  0x8001735: _close
  0x800174d: _fstat
  0x800176d: _isatty
  0x8001783: _lseek
  0x800179d: _sbrk
  0x8001809: SystemInit
  0x800182d: Reset_Handler
  0x800183e: CopyDataInit
  0x8001844: LoopCopyDataInit
  0x8001852: FillZerobss
  0x8001856: LoopFillZerobss
  0x8001862: LoopForever
  0x800187c: Default_Handler
  0x800187d: TIM1_BRK_TIM15_IRQHandler
  0x800187f: HAL_Init
  0x80018b1: HAL_InitTick
  0x8001929: HAL_IncTick
  0x8001951: HAL_GetTick
  0x8001969: HAL_Delay
  0x80019b1: LL_ADC_SetCommonClock
  0x80019d7: LL_ADC_SetCommonPathInternalCh
  0x80019fd: LL_ADC_GetCommonPathInternalCh
  0x8001a19: LL_ADC_SetOffset
  0x8001a61: LL_ADC_GetOffsetChannel
  0x8001a8d: LL_ADC_SetOffsetState
  0x8001ac3: LL_ADC_SetSamplingTimeCommonConfig
  0x8001ae9: LL_ADC_REG_SetSequencerRanks
  0x8001b41: LL_ADC_SetChannelSamplingTime
  0x8001b99: LL_ADC_SetChannelSingleDiff
  0x8001be1: LL_ADC_DisableDeepPowerDown
  0x8001c05: LL_ADC_IsDeepPowerDownEnabled
  0x8001c2d: LL_ADC_EnableInternalRegulator
  0x8001c55: LL_ADC_IsInternalRegulatorEnabled
  0x8001c7d: LL_ADC_IsEnabled
  0x8001ca3: LL_ADC_REG_IsConversionOngoing
  0x8001cc9: LL_ADC_INJ_IsConversionOngoing
  0x8001cf1: HAL_ADC_Init
  0x8001f89: HAL_ADC_ConfigChannel
  0x8002781: __NVIC_SetPriorityGrouping
  0x80027c9: __NVIC_GetPriorityGrouping
  0x80027e5: __NVIC_EnableIRQ
  0x8002821: __NVIC_SetPriority
  0x8002875: NVIC_EncodePriority
  0x80028dd: SysTick_Config
  0x8002921: HAL_NVIC_SetPriorityGrouping
  0x8002937: HAL_NVIC_SetPriority
  0x800296f: HAL_NVIC_EnableIRQ
  0x800298b: HAL_SYSTICK_Config
  0x80029a5: HAL_DFSDM_ChannelInit
  0x8002b25: DFSDM_GetChannelFromInstance
  0x8002bbd: HAL_GPIO_Init
  0x8002ee1: HAL_GPIO_WritePin
  0x8002f11: HAL_GPIO_EXTI_IRQHandler
  0x8002f41: HAL_I2C_Init
  0x800305f: HAL_I2CEx_ConfigAnalogFilter
  0x80030f5: HAL_I2CEx_ConfigDigitalFilter
  0x800318d: HAL_OSPI_Init
  0x80032d9: HAL_OSPI_SetTimeout
  0x80032f9: HAL_OSPIM_Config
  0x80039a1: OSPI_WaitFlagStateUntilTimeout
  0x8003a11: OSPIM_GetConfig
  0x8003b71: HAL_PCD_Init
  0x8003db9: HAL_PCD_Start
  0x8003e17: HAL_PCD_IRQHandler
  0x8004549: HAL_PCD_SetAddress
  0x8004593: HAL_PCD_EP_Open
  0x8004663: HAL_PCD_EP_Close
  0x80046f7: HAL_PCD_EP_Receive
  0x8004773: HAL_PCD_EP_GetRxCount
  0x80047a3: HAL_PCD_EP_Transmit
  0x800481d: HAL_PCD_EP_SetStall
  0x80048e1: HAL_PCD_EP_ClrStall
  0x800498d: HAL_PCD_EP_Flush
  0x80049e7: PCD_WriteEmptyTxFifo
  0x8004af9: PCD_EP_OutXfrComplete_int
  0x8004b95: PCD_EP_OutSetupPacket_int
  0x8004bfd: HAL_PCDEx_SetTxFiFo
  0x8004c8b: HAL_PCDEx_SetRxFiFo
  0x8004cad: HAL_PCDEx_ActivateLPM
  0x8004cf5: HAL_PCDEx_BCD_VBUSDetect
  0x8004de7: HAL_PCDEx_DeActivateBCD
  0x8004e2f: HAL_PCDEx_BCD_Callback
  0x8004e49: HAL_PWR_EnableBkUpAccess
  0x8004e69: HAL_PWREx_GetVoltageRange
  0x8004ea9: HAL_PWREx_ControlVoltageScaling
  0x8004ff1: HAL_PWREx_EnableVddUSB
  0x8005011: HAL_RCC_OscConfig
  0x800585d: HAL_RCC_ClockConfig
  0x8005ab5: HAL_RCC_GetSysClockFreq
  0x8005bcd: HAL_RCC_GetHCLKFreq
  0x8005be5: HAL_RCC_GetPCLK1Freq
  0x8005c11: HAL_RCC_GetPCLK2Freq
  0x8005c3d: RCC_SetFlashLatencyFromMSIRange
  0x8005cf1: RCC_GetSysClockFreqFromPLLSource
  0x8005dc1: HAL_RCCEx_PeriphCLKConfig
  0x8006421: HAL_RCCEx_EnableMSIPLLMode
  0x8006441: RCCEx_PLLSAI1_Config
  0x8006629: RCCEx_PLLSAI2_Config
  0x8006811: HAL_SPI_Init
  0x8006957: HAL_UART_Init
  0x80069f7: HAL_UART_Transmit
  0x8006b25: HAL_UART_Receive
  0x8006ccd: UART_SetConfig
  0x800725d: UART_AdvFeatureConfig
  0x80073a1: UART_CheckIdleState
  0x8007437: UART_WaitOnFlagUntilTimeout
  0x80075c7: HAL_UARTEx_DisableFifoMode
  0x8007639: HAL_UARTEx_SetTxFifoThreshold
  0x80076b5: HAL_UARTEx_SetRxFifoThreshold
  0x8007731: UARTEx_SetNbDataToProcess
  0x80077cd: USB_CoreInit
  0x8007825: USB_SetTurnaroundTime
  0x800795d: USB_EnableGlobalInt
  0x800797f: USB_DisableGlobalInt
  0x80079a1: USB_SetCurrentMode
  0x8007a39: USB_DevInit
  0x8007cd1: USB_FlushTxFifo
  0x8007d35: USB_FlushRxFifo
  0x8007d91: USB_SetDevSpeed
  0x8007dc3: USB_GetDevSpeed
  0x8007e01: USB_ActivateEndpoint
  0x8007f11: USB_DeactivateEndpoint
  0x80080c9: USB_EPStartXfer
  0x8008481: USB_EP0StartXfer
  0x80086bd: USB_WritePacket
  0x8008731: USB_ReadPacket
  0x80087e1: USB_EPSetStall
  0x80088bd: USB_EPClearStall
  0x8008989: USB_SetDevAddress
  0x80089d5: USB_DevConnect
  0x8008a17: USB_DevDisconnect
  0x8008a59: USB_ReadInterrupts
  0x8008a7f: USB_ReadDevAllOutEpInterrupt
  0x8008ab3: USB_ReadDevAllInEpInterrupt
  0x8008ae7: USB_ReadDevOutEPInterrupt
  0x8008b23: USB_ReadDevInEPInterrupt
  0x8008b7f: USB_GetMode
  0x8008b9b: USB_ActivateSetup
  0x8008be1: USB_EP0_OutStart
  0x8008c71: USB_CoreReset
  0x8008cd5: MX_FATFS_Init
  0x8008cf9: USER_initialize
  0x8008d21: USER_status
  0x8008d49: USER_read
  0x8008d67: USER_write
  0x8008d85: USER_ioctl
  0x8008da7: USBD_MSC_Init
  0x8008e41: USBD_MSC_DeInit
  0x8008e99: USBD_MSC_Setup
  0x800907d: USBD_MSC_DataIn
  0x800909d: USBD_MSC_DataOut
  0x80090bd: USBD_MSC_GetHSCfgDesc
  0x80090dd: USBD_MSC_GetFSCfgDesc
  0x80090fd: USBD_MSC_GetOtherSpeedCfgDesc
  0x800911d: USBD_MSC_GetDeviceQualifierDescriptor
  0x800913d: USBD_MSC_RegisterStorage
  0x8009167: MSC_BOT_Init
  0x80091d7: MSC_BOT_Reset
  0x8009223: MSC_BOT_DeInit
  0x800924b: MSC_BOT_DataIn
  0x80092b7: MSC_BOT_DataOut
  0x8009319: MSC_BOT_CBW_Decode
  0x8009431: MSC_BOT_SendData
  0x8009491: MSC_BOT_SendCSW
  0x80094f1: MSC_BOT_Abort
  0x8009555: MSC_BOT_CplClrFeature
  0x80095b1: SCSI_ProcessCmd
  0x80098ad: SCSI_TestUnitReady
  0x800994d: SCSI_Inquiry
  0x8009a35: SCSI_ReadCapacity10
  0x8009b1f: SCSI_ReadCapacity16
  0x8009c73: SCSI_ReadFormatCapacity
  0x8009d59: SCSI_ModeSense6
  0x8009db1: SCSI_ModeSense10
  0x8009e09: SCSI_RequestSense
  0x8009f07: SCSI_SenseCode
  0x8009f95: SCSI_StartStopUnit
  0x800a037: SCSI_AllowPreventRemovable
  0x800a089: SCSI_Read10
  0x800a1c9: SCSI_Read12
  0x800a31f: SCSI_Write10
  0x800a4a9: SCSI_Write12
  0x800a653: SCSI_Verify10
  0x800a6c5: SCSI_CheckAddressRange
  0x800a715: SCSI_ProcessRead
  0x800a807: SCSI_ProcessWrite
  0x800a919: SCSI_UpdateBotData
  0x800a96d: USBD_Init
  0x800a9e9: USBD_RegisterClass
  0x800aa51: USBD_Start
  0x800aa69: USBD_RunTestMode
  0x800aa7f: USBD_SetClassConfig
  0x800aab7: USBD_ClrClassConfig
  0x800aae7: USBD_LL_SetupStage
  0x800ab91: USBD_LL_DataOutStage
  0x800ac57: USBD_LL_DataInStage
  0x800ad83: USBD_LL_Reset
  0x800ae1f: USBD_LL_SetSpeed
  0x800ae3f: USBD_LL_Suspend
  0x800ae6b: USBD_LL_Resume
  0x800ae9b: USBD_LL_SOF
  0x800aedf: USBD_LL_IsoINIncomplete
  0x800af2b: USBD_LL_IsoOUTIncomplete
  0x800af77: USBD_LL_DevConnected
  0x800af8d: USBD_LL_DevDisconnected
  0x800afc5: SWAPBYTE
  0x800b001: USBD_StdDevReq
  0x800b0dd: USBD_StdItfReq
  0x800b16f: USBD_StdEPReq
  0x800b435: USBD_GetDescriptor
  0x800b75d: USBD_SetAddress
  0x800b7e5: USBD_SetConfig
  0x800b931: USBD_GetConfig
  0x800b99d: USBD_GetStatus
  0x800ba05: USBD_SetFeature
  0x800ba2d: USBD_ClrFeature
  0x800ba71: USBD_ParseSetupRequest
  0x800bae5: USBD_CtlError
  0x800bb07: USBD_GetString
  0x800bb93: USBD_GetLen
  0x800bbc7: USBD_CtlSendData
  0x800bbfd: USBD_CtlContinueSendData
  0x800bc1f: USBD_CtlContinueRx
  0x800bc41: USBD_CtlSendStatus
  0x800bc67: USBD_CtlReceiveStatus
  0x800bc8d: FATFS_LinkDriverEx
  0x800bd25: FATFS_LinkDriver
  0x800bd45: MX_USB_DEVICE_Init
  0x800bda5: USBD_FS_DeviceDescriptor
  0x800bdc9: USBD_FS_LangIDStrDescriptor
  0x800bded: USBD_FS_ProductStrDescriptor
  0x800be29: USBD_FS_ManufacturerStrDescriptor
  0x800be51: USBD_FS_SerialStrDescriptor
  0x800be75: USBD_FS_ConfigStrDescriptor
  0x800beb1: USBD_FS_InterfaceStrDescriptor
  0x800beed: USBD_FS_USR_BOSDescriptor
  0x800bf11: Get_SerialNum
  0x800bf69: IntToUnicode
  0x800bfe7: STORAGE_Init_FS
  0x800bfff: STORAGE_GetCapacity_FS
  0x800c029: STORAGE_IsReady_FS
  0x800c041: STORAGE_IsWriteProtected_FS
  0x800c059: STORAGE_Read_FS
  0x800c0bd: STORAGE_Write_FS
  0x800c115: STORAGE_GetMaxLun_FS
  0x800c125: HAL_PCD_MspInit
  0x800c24d: HAL_PCD_SetupStageCallback
  0x800c271: HAL_PCD_DataOutStageCallback
  0x800c2a7: HAL_PCD_DataInStageCallback
  0x800c2db: HAL_PCD_SOFCallback
  0x800c2f7: HAL_PCD_ResetCallback
  0x800c335: HAL_PCD_SuspendCallback
  0x800c381: HAL_PCD_ResumeCallback
  0x800c3d1: HAL_PCD_ISOOUTIncompleteCallback
  0x800c3f5: HAL_PCD_ISOINIncompleteCallback
  0x800c419: HAL_PCD_ConnectCallback
  0x800c435: HAL_PCD_DisconnectCallback
  0x800c451: USBD_LL_Init
  0x800c4e5: USBD_LL_Start
  0x800c549: USBD_LL_OpenEP
  0x800c5c5: USBD_LL_CloseEP
  0x800c631: USBD_LL_FlushEP
  0x800c69d: USBD_LL_StallEP
  0x800c709: USBD_LL_ClearStallEP
  0x800c775: USBD_LL_IsStallEP
  0x800c7cd: USBD_LL_SetUSBAddress
  0x800c839: USBD_LL_Transmit
  0x800c8a9: USBD_LL_PrepareReceive
  0x800c919: USBD_LL_GetRxDataSize
  0x800c941: HAL_GPIO_EXTI_Callback
  0x800c965: HAL_PCDEx_LPM_Callback
  0x800ca01: USBD_static_malloc
  0x800ca1d: USBD_static_free
  0x800ca31: SystemClockConfig_Resume
  0x800ca3d: __errno
  0x800ca49: __libc_init_array
  0x800ca91: malloc
  0x800caa1: memmove
  0x800cad5: memset
  0x800cae5: _free_r
  0x800cb85: _malloc_r
  0x800cc39: iprintf
  0x800cc69: putchar
  0x800cc95: _puts_r
  0x800cd71: puts
  0x800cd81: _sbrk_r
  0x800cda1: setvbuf
  0x800cf2d: __swbuf_r
  0x800cfd1: __swsetup_r
  0x800d0ad: __sflush_r
  0x800d1b9: _fflush_r
  0x800d231: std
  0x800d279: _cleanup_r
  0x800d285: __sfmoreglue
  0x800d2b1: __sfp_lock_acquire
  0x800d2bd: __sfp_lock_release
  0x800d2c9: __sinit_lock_acquire
  0x800d2d5: __sinit_lock_release
  0x800d2e1: __sinit
  0x800d351: __sfp
  0x800d3dd: _fwalk_reent
  0x800d41b: __retarget_lock_init_recursive
  0x800d41d: __retarget_lock_acquire_recursive
  0x800d41f: __retarget_lock_release_recursive
  0x800d421: __swhatbuf_r
  0x800d469: __smakebuf_r
  0x800d4e9: __malloc_lock
  0x800d4f5: __malloc_unlock
  0x800d501: __sfputc_r
  0x800d52f: __sfputs_r
  0x800d555: _vfprintf_r
  0x800d7b5: _printf_common
  0x800d891: _printf_i
  0x800dadd: _putc_r
  0x800db6d: __sread
  0x800db8f: __swrite
  0x800dbc7: __sseek
  0x800dbeb: __sclose
  0x800dbf5: _write_r
  0x800dc19: _close_r
  0x800dc39: _fstat_r
  0x800dc5d: _isatty_r
  0x800dc7d: _lseek_r
  0x800dca1: _read_r
  0x800dcc4: __EH_FRAME_BEGIN__
  0x800dcc5: _init
  0x800dcd1: _fini
  0x800dcdc: _etext
  0x800dd7c: AHBPrescTable
  0x800dd8c: APBPrescTable
  0x800dd94: MSIRangeTable
  0x800ddc4: UARTPrescTable
  0x800dddc: numerator.10312
  0x800dde4: denominator.10313
  0x800ddec: STORAGE_Inquirydata_FS
  0x800de10: _global_impure_ptr
  0x800de14: __sf_fake_stderr
  0x800de34: __sf_fake_stdin
  0x800de54: __sf_fake_stdout
  0x800dea8: __exidx_start
  0x800deb0: __exidx_end
  0x800deb4: __init_array_end
  0x800deb8: _sidata
  0x20000000: _sdata
  0x20000004: uwTickPrio
  0x20000008: uwTickFreq
  0x20000009: Stat
  0x2000000c: USER_Driver
  0x20000020: USBD_MSC
  0x20000058: USBD_MSC_CfgHSDesc
  0x20000078: USBD_MSC_CfgFSDesc
  0x20000098: USBD_MSC_OtherSpeedCfgDesc
  0x200000b8: USBD_MSC_DeviceQualifierDesc
  0x200000c4: MSC_Page00_Inquiry_Data
  0x200000cc: MSC_Page80_Inquiry_Data
  0x200000d4: MSC_Mode_Sense6_data
  0x200000ec: MSC_Mode_Sense10_data
  0x20000108: FS_Desc
  0x20000128: USBD_FS_DeviceDesc
  0x2000013c: USBD_FS_BOSDesc
  0x20000148: USBD_LangIDDesc
  0x2000014c: USBD_StringSerial
  0x20000168: DiskImage
  0x20004168: USBD_Storage_Interface_fops_FS
  0x20004188: _impure_ptr
  0x2000418c: impure_data
  0x200041ec: _edata
  0x200041f0: __bss_start__
  0x200041f4: object.10283
  0x2000420c: DFSDM1_Init
  0x20004210: __sbrk_heap_end
  0x20004214: v_dfsdm1ChannelCounter
  0x20004218: a_dfsdm1ChannelHandle
  0x20004238: cfgidx.12269
  0x2000423c: disk
  0x20004248: mem.12474
  0x200044c0: __malloc_free_list
  0x200044c4: __malloc_sbrk_start
  0x200044c8: huart3
  0x20004558: hi2c1
  0x200045a4: hospi1
  0x200045f4: hi2c2
  0x20004640: hspi3
  0x200046a4: hadc1
  0x2000470c: huart1
  0x2000479c: hspi1
  0x20004800: huart2
  0x20004890: hdfsdm1_channel2
  0x200048c8: gHuart
  0x200048cc: uwTick
  0x200048d0: USERPath
  0x200048d4: retUSER
  0x200048d8: USERFile
  0x20004b30: USERFatFS
  0x20004d68: hUsbDeviceFS
  0x20005038: USBD_StrDesc
  0x20005238: hpcd_USB_OTG_FS
  0x20005640: __lock___atexit_recursive_mutex
  0x20005641: __lock___arc4random_mutex
  0x20005642: __lock___env_recursive_mutex
  0x20005643: __lock___sinit_recursive_mutex
  0x20005644: __lock___malloc_recursive_mutex
  0x20005645: __lock___at_quick_exit_mutex
  0x20005646: __lock___dd_hash_mutex
  0x20005647: __lock___tz_mutex
  0x20005648: __lock___sfp_recursive_mutex
  0x2000564c: errno
  0x20005650: _end
  0x200a0000: _estack
  0xf1e0f85f: BootRAM
