interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  ._user_stack:
    base_addr: 0x10000000
    permissions: rw-
    size: 0x7f00
  UNINIT_FIXED_LOC:
    base_addr: 0x80ff000
    permissions: rw-
    size: 0xd8
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: WiFi_HTTP_Server.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1b758
symbols:
  0x0: reent.c
  0x7f00: _Min_Stack_Size
  0x10000: _Min_Heap_Size
  0x8000000: g_pfnVectors
  0x80001c1: __do_global_dtors_aux
  0x80001e5: frame_dummy
  0x8000201: strlen
  0x8000211: memchr
  0x80002b1: __aeabi_uldivmod
  0x80002e1: __udivmoddi4
  0x80005a5: __aeabi_idiv0
  0x80005a9: Reset_Handler
  0x80005b4: CopyDataInit
  0x80005bc: LoopCopyDataInit
  0x80005ca: FillZerobss
  0x80005d0: LoopFillZerobss
  0x80005de: LoopForever
  0x80005f8: Default_Handler
  0x80005f9: TIM1_BRK_TIM15_IRQHandler
  0x80005fd: GetPage
  0x8000681: GetBank
  0x800071d: FLASH_Init
  0x8000781: FLASH_Erase_Size
  0x800083d: FLASH_Write
  0x80008d9: main
  0x8000959: wifi_start
  0x80009c9: wifi_connect
  0x8000b8d: wifi_server
  0x8000cb5: WebServerProcess
  0x8001025: SendWebPage
  0x8001341: SystemClock_Config
  0x80013b5: __io_putchar
  0x80013d9: __io_getchar
  0x8001409: HAL_GPIO_EXTI_Callback
  0x8001435: SPI3_IRQHandler
  0x8001449: Button_ISR
  0x8001469: findchar_fast
  0x800148b: get_token_to_eol
  0x80016dd: is_complete
  0x80017a1: parse_token
  0x8001849: parse_http_version
  0x8001955: parse_headers
  0x8001b25: parse_request
  0x8001d39: phr_parse_request
  0x8001de1: NMI_Handler
  0x8001def: HardFault_Handler
  0x8001df7: MemManage_Handler
  0x8001dff: BusFault_Handler
  0x8001e07: UsageFault_Handler
  0x8001e0f: SVC_Handler
  0x8001e1d: DebugMon_Handler
  0x8001e2b: PendSV_Handler
  0x8001e39: SysTick_Handler
  0x8001e45: EXTI1_IRQHandler
  0x8001e53: EXTI15_10_IRQHandler
  0x8001e63: _getpid
  0x8001e73: _kill
  0x8001e93: _exit
  0x8001ea7: _read
  0x8001ec9: _write
  0x8001f01: _close
  0x8001f19: _fstat
  0x8001f39: _isatty
  0x8001f4f: _lseek
  0x8001f69: _sbrk
  0x8001fc1: SystemInit
  0x800202d: Hex2Num
  0x8002081: ParseHexNumber
  0x8002101: ParseNumber
  0x8002189: ParseMAC
  0x80021df: ParseIP
  0x8002235: AT_ParseInfo
  0x8002321: AT_ParseConnSettings
  0x8002481: AT_ParseIsConnected
  0x80024ad: AT_ExecuteCommand
  0x8002579: AT_RequestSendData
  0x8002665: AT_RequestReceiveData
  0x8002791: ES_WIFI_Init
  0x80027ed: ES_WIFI_RegisterBusIO
  0x8002855: ES_WIFI_Connect
  0x8002955: ES_WIFI_IsConnected
  0x80029ad: ES_WIFI_GetNetworkSettings
  0x8002a01: ES_WIFI_GetMACAddress
  0x8002a65: ES_WIFI_StartServerSingleConn
  0x8002bbd: ES_WIFI_WaitServerConnection
  0x8002dad: ES_WIFI_CloseServerConnection
  0x8002e21: ES_WIFI_StopServerSingleConn
  0x8002ea1: ES_WIFI_SendData
  0x8002fad: ES_WIFI_ReceiveData
  0x80030c1: SPI_WIFI_MspInit
  0x8003239: SPI_WIFI_Init
  0x80032f5: SPI_WIFI_ResetModule
  0x80033d5: SPI_WIFI_DeInit
  0x80033e9: wait_cmddata_rdy_high
  0x800342d: wait_cmddata_rdy_rising_event
  0x800346d: wait_spi_rx_event
  0x80034ad: wait_spi_tx_event
  0x80034ed: SPI_WIFI_ReceiveData
  0x80035e1: SPI_WIFI_SendData
  0x80036bd: SPI_WIFI_Delay
  0x80036d5: SPI_WIFI_DelayUs
  0x8003779: HAL_SPI_RxCpltCallback
  0x80037a1: HAL_SPI_TxCpltCallback
  0x80037c9: SPI_WIFI_ISR
  0x80037e9: WIFI_Init
  0x8003841: WIFI_Connect
  0x8003885: WIFI_GetMAC_Address
  0x80038b1: WIFI_GetIP_Address
  0x80038e9: WIFI_StartServer
  0x8003949: WIFI_WaitServerConnection
  0x80039cd: WIFI_CloseServerConnection
  0x80039f9: WIFI_StopServer
  0x8003a29: WIFI_SendData
  0x8003a6d: WIFI_ReceiveData
  0x8003ab1: HTS221_T_Init
  0x8003b0b: HTS221_T_ReadTemp
  0x8003c19: BSP_LED_Init
  0x8003c79: BSP_LED_On
  0x8003ca5: BSP_LED_Off
  0x8003cd1: BSP_PB_Init
  0x8003d7d: BSP_COM_Init
  0x8003e55: I2Cx_MspInit
  0x8003f05: I2Cx_Init
  0x8003f61: I2Cx_ReadMultiple
  0x8003fbb: I2Cx_WriteMultiple
  0x8004015: I2Cx_Error
  0x8004035: SENSOR_IO_Init
  0x8004049: SENSOR_IO_Write
  0x800407d: SENSOR_IO_Read
  0x80040b9: SENSOR_IO_ReadMultiple
  0x80040f5: BSP_TSENSOR_Init
  0x800412d: BSP_TSENSOR_ReadTemp
  0x8004149: HAL_Init
  0x8004179: HAL_MspInit
  0x8004189: HAL_InitTick
  0x8004201: HAL_IncTick
  0x8004229: HAL_GetTick
  0x8004241: HAL_Delay
  0x8004289: __NVIC_SetPriorityGrouping
  0x80042d1: __NVIC_GetPriorityGrouping
  0x80042ed: __NVIC_EnableIRQ
  0x8004329: __NVIC_SetPriority
  0x800437d: NVIC_EncodePriority
  0x80043e5: SysTick_Config
  0x8004429: HAL_NVIC_SetPriorityGrouping
  0x800443f: HAL_NVIC_SetPriority
  0x8004477: HAL_NVIC_EnableIRQ
  0x8004493: HAL_SYSTICK_Config
  0x80044ab: HAL_DMA_Abort_IT
  0x8004569: HAL_FLASH_Program
  0x8004641: HAL_FLASH_Unlock
  0x8004685: HAL_FLASH_Lock
  0x80046a5: HAL_FLASH_GetError
  0x80046bd: FLASH_WaitForLastOperation
  0x800476d: FLASH_Program_DoubleWord
  0x80047b9: FLASH_Program_Fast
  0x8004825: HAL_FLASHEx_Erase
  0x800495d: FLASH_MassErase
  0x80049cd: FLASH_PageErase
  0x8004a55: FLASH_FlushCaches
  0x8004ae9: HAL_GPIO_Init
  0x8004e0d: HAL_GPIO_ReadPin
  0x8004e3d: HAL_GPIO_WritePin
  0x8004e6d: HAL_GPIO_EXTI_IRQHandler
  0x8004e9d: HAL_I2C_Init
  0x8004fbb: HAL_I2C_DeInit
  0x8005019: HAL_I2C_MspInit
  0x800502d: HAL_I2C_MspDeInit
  0x8005041: HAL_I2C_Mem_Write
  0x8005269: HAL_I2C_Mem_Read
  0x800549d: I2C_RequestMemoryWrite
  0x8005545: I2C_RequestMemoryRead
  0x80055ed: I2C_Flush_TXDR
  0x8005635: I2C_WaitOnFlagUntilTimeout
  0x80056b5: I2C_WaitOnTXISFlagUntilTimeout
  0x8005735: I2C_WaitOnSTOPFlagUntilTimeout
  0x80057ad: I2C_IsErrorOccurred
  0x8005985: I2C_TransferConfig
  0x80059e9: HAL_I2CEx_ConfigAnalogFilter
  0x8005a81: HAL_PWREx_GetVoltageRange
  0x8005ac1: HAL_RCC_OscConfig
  0x800630d: HAL_RCC_ClockConfig
  0x8006565: HAL_RCC_GetSysClockFreq
  0x800667d: HAL_RCC_GetHCLKFreq
  0x8006695: HAL_RCC_GetPCLK1Freq
  0x80066c1: HAL_RCC_GetPCLK2Freq
  0x80066ed: RCC_SetFlashLatencyFromMSIRange
  0x80067a1: RCC_GetSysClockFreqFromPLLSource
  0x8006871: HAL_SPI_Init
  0x8006a09: HAL_SPI_DeInit
  0x8006a59: HAL_SPI_MspInit
  0x8006a6d: HAL_SPI_MspDeInit
  0x8006a81: HAL_SPI_Receive
  0x8006e53: HAL_SPI_TransmitReceive
  0x800741d: HAL_SPI_Transmit_IT
  0x8007561: HAL_SPI_Receive_IT
  0x8007711: HAL_SPI_TransmitReceive_IT
  0x80078c1: HAL_SPI_IRQHandler
  0x8007ac1: HAL_SPI_TxRxCpltCallback
  0x8007ad5: HAL_SPI_ErrorCallback
  0x8007ae9: SPI_DMAAbortOnError
  0x8007b15: SPI_2linesRxISR_8BIT
  0x8007bf9: SPI_2linesRxISR_8BITCRC
  0x8007c51: SPI_2linesTxISR_8BIT
  0x8007d0d: SPI_2linesRxISR_16BIT
  0x8007d89: SPI_2linesRxISR_16BITCRC
  0x8007dbd: SPI_2linesTxISR_16BIT
  0x8007e47: SPI_RxISR_8BITCRC
  0x8007e85: SPI_RxISR_8BIT
  0x8007f11: SPI_RxISR_16BITCRC
  0x8007f45: SPI_RxISR_16BIT
  0x8007fcd: SPI_TxISR_8BIT
  0x800802d: SPI_TxISR_16BIT
  0x800808d: SPI_WaitFlagStateUntilTimeout
  0x800819d: SPI_WaitFifoStateUntilTimeout
  0x80082c9: SPI_EndRxTransaction
  0x8008379: SPI_EndRxTxTransaction
  0x8008405: SPI_CloseRxTx_ISR
  0x80084bd: SPI_CloseRx_ISR
  0x8008549: SPI_CloseTx_ISR
  0x80085c7: HAL_UART_Init
  0x8008667: HAL_UART_MspInit
  0x800867b: HAL_UART_Transmit
  0x80087a9: HAL_UART_Receive
  0x8008951: UART_SetConfig
  0x8008ee1: UART_AdvFeatureConfig
  0x8009025: UART_CheckIdleState
  0x80090bb: UART_WaitOnFlagUntilTimeout
  0x800924d: __assert_func
  0x8009289: __errno
  0x8009295: fiprintf
  0x80092b9: __libc_init_array
  0x8009301: malloc
  0x8009311: memcmp
  0x800932d: memcpy
  0x8009349: memmove
  0x800937d: memset
  0x800938d: _free_r
  0x800942d: _malloc_r
  0x80094e1: __sfputc_r
  0x800950f: __sfputs_r
  0x8009535: _vfprintf_r
  0x8009795: _printf_common
  0x8009871: _printf_i
  0x8009abd: iprintf
  0x8009aed: putchar
  0x8009b19: _puts_r
  0x8009bf5: puts
  0x8009c05: _sbrk_r
  0x8009c25: siprintf
  0x8009c65: strcat
  0x8009c83: strncmp
  0x8009ca7: strncpy
  0x8009ccd: strstr
  0x8009cfd: strtok
  0x8009d65: __strtok_r
  0x8009db5: __swbuf_r
  0x8009e59: __swsetup_r
  0x8009f35: abort
  0x8009f45: __sflush_r
  0x800a051: _fflush_r
  0x800a0c9: std
  0x800a111: _cleanup_r
  0x800a11d: __sfmoreglue
  0x800a149: __sfp_lock_acquire
  0x800a155: __sfp_lock_release
  0x800a161: __sinit_lock_acquire
  0x800a16d: __sinit_lock_release
  0x800a179: __sinit
  0x800a1e9: __sfp
  0x800a275: _fwalk_reent
  0x800a2b3: __retarget_lock_init_recursive
  0x800a2b5: __retarget_lock_acquire_recursive
  0x800a2b7: __retarget_lock_release_recursive
  0x800a2b9: __swhatbuf_r
  0x800a301: __smakebuf_r
  0x800a381: __malloc_lock
  0x800a38d: __malloc_unlock
  0x800a399: _realloc_r
  0x800a3e5: __ssputs_r
  0x800a49d: _svfiprintf_r
  0x800a69d: _putc_r
  0x800a72d: _raise_r
  0x800a77d: raise
  0x800a78d: _kill_r
  0x800a7b1: _getpid_r
  0x800a7b5: __sread
  0x800a7d7: __swrite
  0x800a80f: __sseek
  0x800a833: __sclose
  0x800a83d: _write_r
  0x800a861: _close_r
  0x800a881: _fstat_r
  0x800a8a5: _isatty_r
  0x800a8c5: _lseek_r
  0x800a8e9: _malloc_usable_size_r
  0x800a8f9: _read_r
  0x800a91c: __EH_FRAME_BEGIN__
  0x800a91d: _init
  0x800a929: _fini
  0x800a934: _etext
  0x800b4b0: ranges.6152
  0x800b4d0: ranges2.6198
  0x800b4e0: AHBPrescTable
  0x800b4f0: APBPrescTable
  0x800b4f8: MSIRangeTable
  0x800b528: UARTPrescTable
  0x800b57c: _global_impure_ptr
  0x800b62c: __sf_fake_stderr
  0x800b64c: __sf_fake_stdin
  0x800b66c: __sf_fake_stdout
  0x800b68c: __exidx_start
  0x800b694: __exidx_end
  0x800b698: __init_array_end
  0x800b69c: _sidata
  0x80ff000: __uninited_region_start__
  0x20000000: lUserConfigPtr
  0x20000004: token_char_map
  0x20000008: SystemCoreClock
  0x2000000c: HTS221_T_Drv
  0x2000001c: GPIO_PORT
  0x20000020: BUTTON_PORT
  0x20000024: COM_USART
  0x20000028: COM_TX_PORT
  0x2000002c: COM_RX_PORT
  0x20000030: uwTickPrio
  0x20000034: uwTickFreq
  0x20000038: pFlash
  0x20000058: _impure_ptr
  0x2000005c: impure_data
  0x200000bc: _edata
  0x200000c0: __bss_start__
  0x200000c4: object.10283
  0x200000dc: button_flag
  0x200000e0: user_config
  0x200001b8: http
  0x200005b8: IP_Addr
  0x200005bc: LedState
  0x200005c0: heap_end.6585
  0x200005c4: issue15
  0x200005c8: spi_rx_event
  0x200005cc: spi_tx_event
  0x200005d0: cmddata_rdy_rising_event
  0x200005d4: cycle_per_loop.11352
  0x200005d8: tsensor_drv
  0x200005dc: __malloc_free_list
  0x200005e0: __malloc_sbrk_start
  0x200005e4: hspi
  0x20000648: EsWifiObj
  0x20000f48: hDiscoUart
  0x20000fd8: hI2cHandler
  0x20001024: uwTick
  0x20001028: __lock___atexit_recursive_mutex
  0x20001029: __lock___arc4random_mutex
  0x2000102a: __lock___env_recursive_mutex
  0x2000102b: __lock___sinit_recursive_mutex
  0x2000102c: __lock___malloc_recursive_mutex
  0x2000102d: __lock___at_quick_exit_mutex
  0x2000102e: __lock___dd_hash_mutex
  0x2000102f: __lock___tz_mutex
  0x20001030: __lock___sfp_recursive_mutex
  0x20001034: errno
  0x20001038: __bss_end__
  0x20018000: _estack
  0xf1e0f85f: BootRAM
