interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: firmware.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x16ac8
symbols:
  0x0: LD_FLASH_OFFSET
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0xa0000: LD_MAX_DATA_SIZE
  0x200000: LD_MAX_SIZE
  0x8000000: g_pfnVectors
  0x80001c1: __aeabi_drsub
  0x80001c9: __subdf3
  0x80001cd: __aeabi_dadd
  0x8000445: __floatunsidf
  0x8000465: __aeabi_i2d
  0x8000489: __aeabi_f2d
  0x80004cd: __floatundidf
  0x80004dd: __aeabi_l2d
  0x8000539: __muldf3
  0x800078d: __divdf3
  0x800095d: __gedf2
  0x8000965: __ledf2
  0x800096d: __nedf2
  0x80009e9: __aeabi_cdrcmple
  0x80009f9: __aeabi_cdcmpeq
  0x8000a09: __aeabi_dcmpeq
  0x8000a1d: __aeabi_dcmplt
  0x8000a31: __aeabi_dcmple
  0x8000a45: __aeabi_dcmpge
  0x8000a59: __aeabi_dcmpgt
  0x8000a6d: __aeabi_d2uiz
  0x8000aad: __aeabi_uldivmod
  0x8000add: __aeabi_idiv0
  0x8000ae1: strcmp
  0x8000af5: strlen
  0x8000b05: __do_global_dtors_aux
  0x8000b29: frame_dummy
  0x8000b45: SystemClock_Config
  0x8000c31: HAL_MspInit
  0x8000c35: HAL_InitTick
  0x8000c81: HAL_Init
  0x8000ca1: HAL_IncTick
  0x8000cb9: HAL_GetTick
  0x8000cc5: HAL_NVIC_SetPriorityGrouping
  0x8000ce9: HAL_NVIC_SetPriority
  0x8000d4d: HAL_NVIC_EnableIRQ
  0x8000d69: HAL_NVIC_DisableIRQ
  0x8000d91: HAL_SYSTICK_Config
  0x8000dbd: HAL_NVIC_ClearPendingIRQ
  0x8000ddd: HAL_SYSTICK_Callback
  0x8000ddf: HAL_SYSTICK_IRQHandler
  0x8000de7: HAL_DAC_DeInit
  0x8000e03: HAL_DAC_Stop
  0x8000e1f: HAL_DMA_Abort
  0x8000e87: HAL_DMA_Abort_IT
  0x8000ef5: HAL_GPIO_EXTI_IRQHandler
  0x8000f0d: HAL_PWR_EnableBkUpAccess
  0x8000f1d: HAL_PWREx_GetVoltageRange
  0x8000f41: HAL_PWREx_ControlVoltageScaling
  0x8000ff9: HAL_PWREx_EnableVddIO2
  0x8001009: RCC_SetFlashLatencyFromMSIRange
  0x8001085: HAL_RCC_GetSysClockFreq
  0x8001121: HAL_RCC_OscConfig
  0x800167d: HAL_RCC_ClockConfig
  0x8001871: HAL_RCC_GetPCLK1Freq
  0x8001895: HAL_RCC_GetPCLK2Freq
  0x80018b9: RCCEx_PLLSAI1_Config
  0x80019c1: RCCEx_PLLSAI2_Config.constprop.0
  0x8001a8d: HAL_RCCEx_PeriphCLKConfig
  0x8001eb9: HAL_RCCEx_EnableMSIPLLMode
  0x8001ec9: HAL_TIM_PWM_PulseFinishedCallback
  0x8001ecb: HAL_TIM_TriggerCallback
  0x8001ecd: HAL_TIM_IRQHandler
  0x800202d: TIM_Base_SetConfig
  0x80020f9: HAL_TIM_Base_Init
  0x8002159: HAL_TIMEx_CommutCallback
  0x800215b: HAL_TIMEx_BreakCallback
  0x800215d: HAL_TIMEx_Break2Callback
  0x8002161: UART_EndRxTransfer
  0x80021b9: UART_TxISR_16BIT.part.0
  0x80021df: UART_TxISR_8BIT
  0x800220f: UART_TxISR_16BIT
  0x8002243: UART_TxISR_16BIT_FIFOEN.part.0
  0x800226f: UART_TxISR_8BIT_FIFOEN
  0x80022b9: UART_TxISR_16BIT_FIFOEN
  0x8002307: HAL_UART_MspInit
  0x8002309: HAL_UART_Transmit_IT
  0x80023d1: UART_DMAAbortOnError
  0x80023e5: HAL_UARTEx_RxEventCallback
  0x80023e9: HAL_UART_IRQHandler
  0x80026d1: UART_RxISR_16BIT.part.0
  0x8002739: UART_RxISR_16BIT
  0x8002777: UART_RxISR_8BIT
  0x80027c1: UART_RxISR_8BIT_FIFOEN
  0x800293d: UART_RxISR_16BIT_FIFOEN
  0x8002ab5: HAL_HalfDuplex_EnableTransmitter
  0x8002b01: HAL_HalfDuplex_EnableReceiver
  0x8002b4d: HAL_UART_GetState
  0x8002b59: UART_SetConfig
  0x8002e25: UART_AdvFeatureConfig
  0x8002ecd: UART_WaitOnFlagUntilTimeout
  0x8002f91: UART_CheckIdleState
  0x8002ffb: HAL_UART_Init
  0x800305b: HAL_HalfDuplex_Init
  0x80030c5: UART_Start_Receive_IT
  0x80031e9: HAL_UART_Receive_IT
  0x800323d: HAL_UARTEx_RxFifoFullCallback
  0x800323f: HAL_UARTEx_TxFifoEmptyCallback
  0x8003241: HAL_UARTEx_EnableStopMode
  0x800326d: HAL_UARTEx_DisableStopMode
  0x8003299: set_GPIO_Port_Clock
  0x80033b9: HAL_DAC_MspDeInit
  0x80033e5: dac_stop
  0x800341d: pwm_stop
  0x800347d: getCurrentMillis
  0x8003481: osSystickHandler
  0x8003483: SysTick_Handler
  0x8003495: enableClock
  0x8003535: configHSECapacitorTuning
  0x8003539: configIPClock
  0x8003569: dwt_init
  0x80035a1: hw_config_init
  0x80035bb: _ZNSt14_Function_baseD1Ev
  0x80035cd: HAL_GPIO_EXTI_Callback
  0x80035f9: EXTI0_IRQHandler
  0x80035ff: EXTI1_IRQHandler
  0x8003605: EXTI2_IRQHandler
  0x800360b: EXTI3_IRQHandler
  0x8003611: EXTI4_IRQHandler
  0x8003617: EXTI9_5_IRQHandler
  0x800362d: EXTI15_10_IRQHandler
  0x8003645: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x80036cd: _GLOBAL__sub_D__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x80036e9: LL_GPIO_SetPinPull
  0x8003713: pin_in_pinmap
  0x8003731: pin_function
  0x800385d: pinmap_pinout
  0x8003885: pinmap_find_peripheral
  0x800389b: pinmap_peripheral
  0x80038a7: pinmap_find_pin
  0x80038bd: pinmap_pin
  0x80038c9: pinmap_find_function
  0x80038df: pinmap_function
  0x80038e9: pinmap_merge_peripheral
  0x80038fb: _Error_Handler
  0x80038fd: SystemInit
  0x8003941: get_timer_obj
  0x8003945: enableTimerClock
  0x8003aa5: disableTimerClock
  0x8003b8d: getTimerUpIrq
  0x8003c31: getTimerCCIrq
  0x8003cd9: HAL_TIM_Base_MspInit
  0x8003d29: uart_init.part.0
  0x8004011: uart_init
  0x8004019: serial_rx_active
  0x800403d: serial_tx_active
  0x8004061: uart_getc
  0x8004099: uart_attach_rx_callback
  0x80040d9: uart_attach_tx_callback
  0x800411d: uart_enable_tx
  0x800413d: uart_enable_rx
  0x800415d: HAL_UART_RxCpltCallback
  0x8004165: HAL_UART_TxCpltCallback
  0x800416d: HAL_UART_ErrorCallback
  0x80041b5: USART1_IRQHandler
  0x80041cd: USART2_IRQHandler
  0x80041e9: USART3_IRQHandler
  0x8004205: UART4_IRQHandler
  0x800421d: UART5_IRQHandler
  0x8004235: LPUART1_IRQHandler
  0x800424d: HAL_UARTEx_WakeupCallback
  0x8004259: _sbrk
  0x8004295: _exit
  0x8004299: _kill
  0x80042a9: _getpid
  0x80042ad: _ZN18ArduinoJson6193_F114CollectionData7addSlotEPNS_10MemoryPoolE
  0x80042e9: setup
  0x8004339: _ZN18ArduinoJson6193_F111FloatTraitsIdLj8EE24positiveBinaryPowerOfTenEi
  0x8004351: _ZN18ArduinoJson6193_F111parseNumberEPKcRNS_11VariantDataE
  0x80045d9: _ZN18ArduinoJson6193_F116JsonDeserializerINS_13BoundedReaderIPhvEENS_11StringMoverEE7currentEv
  0x80045fd: _ZN18ArduinoJson6193_F116JsonDeserializerINS_13BoundedReaderIPhvEENS_11StringMoverEE21skipSpacesAndCommentsEv
  0x8004641: _ZN18ArduinoJson6193_F116JsonDeserializerINS_13BoundedReaderIPhvEENS_11StringMoverEE3eatEc
  0x8004659: _ZN18ArduinoJson6193_F116JsonDeserializerINS_13BoundedReaderIPhvEENS_11StringMoverEE22canBeInNonQuotedStringEc
  0x8004687: _ZN18ArduinoJson6193_F14Utf815encodeCodepointINS_11StringMoverEEEvmRT_
  0x800471d: _ZN18ArduinoJson6193_F116JsonDeserializerINS_13BoundedReaderIPhvEENS_11StringMoverEE17parseQuotedStringEv
  0x80047fd: _ZN18ArduinoJson6193_F116JsonDeserializerINS_13BoundedReaderIPhvEENS_11StringMoverEE12parseVariantINS_14AllowAllFilterEEEbRNS_11VariantDataET_NS_12NestingLimitE
  0x800499f: _ZN18ArduinoJson6193_F116JsonDeserializerINS_13BoundedReaderIPhvEENS_11StringMoverEE11parseObjectINS_14AllowAllFilterEEEbRNS_14CollectionDataET_NS_12NestingLimitE
  0x8004adf: _ZN18ArduinoJson6193_F117CountingDecoratorINS_18StaticStringWriterEE5writeEPKhj
  0x8004b07: _ZN18ArduinoJson6193_F113TextFormatterINS_18StaticStringWriterEE8writeRawEPKc
  0x8004b21: _ZN18ArduinoJson6193_F113TextFormatterINS_18StaticStringWriterEE12writeIntegerIyEENS_9enable_ifIXsrNS_11is_unsignedIT_EE5valueEvE4typeES6_
  0x8004b77: _ZN18ArduinoJson6193_F117CountingDecoratorINS_18StaticStringWriterEE5writeEh
  0x8004b95: _ZN18ArduinoJson6193_F113TextFormatterINS_18StaticStringWriterEE9writeCharEc
  0x8004bd1: _ZN18ArduinoJson6193_F114JsonSerializerINS_18StaticStringWriterEE11visitObjectERKNS_14CollectionDataE
  0x8004c39: _ZNK18ArduinoJson6193_F111VariantData6acceptINS_14JsonSerializerINS_18StaticStringWriterEEEEENT_11result_typeERS5_
  0x8004fe1: _Z6parserPhj
  0x800506d: _Z17serial_read_bytesPhj
  0x8005095: loop
  0x80050fd: _ZN14HardwareSerial9availableEv
  0x800510d: _ZN14HardwareSerial4peekEv
  0x8005127: _ZN14HardwareSerial17availableForWriteEv
  0x8005143: _ZN14HardwareSerial5writeEh
  0x800515b: _ZN14HardwareSerial16_rx_complete_irqEP8serial_s
  0x8005195: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x80051fd: _ZN14HardwareSerial5writeEPKhj
  0x80052e1: _ZN14HardwareSerial5flushEv
  0x80052f5: _ZN14HardwareSerial4initE7PinNameS0_
  0x800531d: _ZN14HardwareSerial5setRxEm
  0x8005365: _ZN14HardwareSerial5setTxEm
  0x80053ad: _ZN14HardwareSerialC1EPv16HalfDuplexMode_t
  0x8005421: _ZN14HardwareSerial18enableHalfDuplexRxEv
  0x800544d: _ZN14HardwareSerial5beginEmh
  0x80054f1: _ZN14HardwareSerial4readEv
  0x8005521: _GLOBAL__sub_I_Serial1
  0x8005535: _ZNSt8functionIFvvEEaSEDn.isra.0
  0x800554d: _Z15get_timer_indexP11TIM_TypeDef
  0x80055e1: _ZN13HardwareTimerD1Ev
  0x8005621: _ZN13HardwareTimer5setupEP11TIM_TypeDef
  0x80056d9: _ZN13HardwareTimerC2EP11TIM_TypeDef
  0x80056f9: TIM1_UP_TIM16_IRQHandler
  0x800571d: TIM1_CC_IRQHandler
  0x8005731: TIM2_IRQHandler
  0x8005745: TIM3_IRQHandler
  0x8005759: TIM4_IRQHandler
  0x800576d: TIM5_IRQHandler
  0x8005781: TIM6_DAC_IRQHandler
  0x8005795: TIM7_IRQHandler
  0x80057a9: TIM8_UP_IRQHandler
  0x80057bd: TIM8_CC_IRQHandler
  0x80057c1: TIM1_BRK_TIM15_IRQHandler
  0x80057d5: TIM1_TRG_COM_TIM17_IRQHandler
  0x80057e9: _ZNKSt8functionIFvvEEclEv
  0x80057fd: _ZN13HardwareTimer14updateCallbackEP17TIM_HandleTypeDef
  0x8005825: HAL_TIM_PeriodElapsedCallback
  0x8005829: _ZN13HardwareTimer22captureCompareCallbackEP17TIM_HandleTypeDef
  0x8005879: HAL_TIM_OC_DelayElapsedCallback
  0x800587d: HAL_TIM_IC_CaptureCallback
  0x8005881: _ZN6Stream9timedReadEv
  0x80058ab: _ZN6Stream9readBytesEPcj
  0x80058cd: _ZN6Stream14readBytesUntilEcPcj
  0x80058fd: _Z7premainv
  0x800590d: main
  0x8005921: _Znwj
  0x8005925: _ZdlPvj
  0x8005929: Reset_Handler
  0x800593a: CopyDataInit
  0x8005940: LoopCopyDataInit
  0x800594e: FillZerobss
  0x8005952: LoopFillZerobss
  0x800595e: LoopForever
  0x8005978: Default_Handler
  0x8005979: DMA2_Channel3_IRQHandler
  0x800597d: pinMode
  0x8005a5d: digitalWrite
  0x8005ad1: millis
  0x8005ad5: delay
  0x8005af1: _Z14serialEventRunv
  0x8005b0d: init
  0x8005b11: yield
  0x8005b15: __udivmoddi4
  0x8005dd9: _ZSt25__throw_bad_function_callv
  0x8005ddf: abort
  0x8005ded: calloc
  0x8005dfd: __libc_init_array
  0x8005e45: malloc
  0x8005e55: free
  0x8005e65: memcpy
  0x8005e81: memset
  0x8005e91: _calloc_r
  0x8005eb1: _free_r
  0x8005f51: _malloc_r
  0x8006005: _sbrk_r
  0x8006025: _raise_r
  0x8006075: raise
  0x8006085: _kill_r
  0x80060a9: _getpid_r
  0x80060ad: __retarget_lock_acquire_recursive
  0x80060af: __retarget_lock_release_recursive
  0x80060b1: __malloc_lock
  0x80060bd: __malloc_unlock
  0x80060c8: __EH_FRAME_BEGIN__
  0x80060c9: _init
  0x80060d5: _fini
  0x80060e0: PinMap_DAC
  0x8006104: PinMap_TIM
  0x80062b4: PinMap_UART_RX
  0x8006338: PinMap_UART_TX
  0x8006440: analogInputPin
  0x8006480: digitalPin
  0x80065cc: CSWTCH.60
  0x80065cf: CSWTCH.61
  0x80065dc: UARTPrescTable
  0x80066bc: pin_map_ll
  0x80066fc: AHBPrescTable
  0x800670c: APBPrescTable
  0x8006714: MSIRangeTable
  0x8006784: _ZZN18ArduinoJson6193_F111FloatTraitsIdLj8EE31negativeBinaryPowerOfTenPlusOneEiE7factors
  0x80067cc: _ZZN18ArduinoJson6193_F111FloatTraitsIdLj8EE24negativeBinaryPowerOfTenEiE7factors
  0x8006814: _ZZN18ArduinoJson6193_F111FloatTraitsIdLj8EE24positiveBinaryPowerOfTenEiE7factors
  0x80068b9: CSWTCH.49
  0x80068c0: CSWTCH.50
  0x80068cc: _ZTV14HardwareSerial
  0x80069b0: __sf_fake_stderr
  0x80069d0: __sf_fake_stdin
  0x80069f0: __sf_fake_stdout
  0x8006a10: __exidx_start
  0x8006a18: __exidx_end
  0x8006a1c: __frame_dummy_init_array_entry
  0x8006a28: __init_array_end
  0x8006a30: _sidata
  0x20000000: _sdata
  0x20000004: uwTickPrio
  0x20000008: GPIOPort
  0x2000002c: SystemCoreClock
  0x20000030: heap_end.11120
  0x20000034: _impure_ptr
  0x20000038: impure_data
  0x20000098: _edata
  0x2000009c: object.10279
  0x200000b4: _ZL13gpio_irq_conf
  0x200001f4: uart_handlers
  0x2000020c: buf
  0x20000210: led_state
  0x20000214: Serial1
  0x2000036c: HardwareTimer_Handle
  0x20000398: g_anOutputPinConfigured
  0x200003bc: __malloc_free_list
  0x200003c0: __malloc_sbrk_start
  0x200003c4: uwTick
  0x200003c8: errno
  0x200003cc: __lock___atexit_recursive_mutex
  0x200003cd: __lock___arc4random_mutex
  0x200003ce: __lock___env_recursive_mutex
  0x200003cf: __lock___sinit_recursive_mutex
  0x200003d0: __lock___malloc_recursive_mutex
  0x200003d1: __lock___at_quick_exit_mutex
  0x200003d2: __lock___dd_hash_mutex
  0x200003d3: __lock___tz_mutex
  0x200003d4: __lock___sfp_recursive_mutex
  0x200003d8: _end
  0x200a0000: _estack
  0xf1e0f85f: BootRAM
