interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: firmware.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x15390
symbols:
  0x0: LD_FLASH_OFFSET
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0xa0000: LD_MAX_DATA_SIZE
  0x200000: LD_MAX_SIZE
  0x8000000: g_pfnVectors
  0x80001bd: __aeabi_uldivmod
  0x80001ed: __aeabi_idiv0
  0x80001f1: __do_global_dtors_aux
  0x8000215: frame_dummy
  0x8000231: SystemClock_Config
  0x800031d: HAL_MspInit
  0x8000321: HAL_InitTick
  0x800036d: HAL_Init
  0x800038d: HAL_IncTick
  0x80003a5: HAL_GetTick
  0x80003b1: HAL_NVIC_SetPriorityGrouping
  0x80003d5: HAL_NVIC_SetPriority
  0x8000439: HAL_NVIC_EnableIRQ
  0x8000455: HAL_NVIC_DisableIRQ
  0x800047d: HAL_SYSTICK_Config
  0x80004a9: HAL_NVIC_ClearPendingIRQ
  0x80004c9: HAL_SYSTICK_Callback
  0x80004cb: HAL_SYSTICK_IRQHandler
  0x80004d3: HAL_DAC_DeInit
  0x80004ef: HAL_DAC_Stop
  0x800050b: HAL_DMA_Abort
  0x8000573: HAL_DMA_Abort_IT
  0x80005e1: HAL_GPIO_EXTI_IRQHandler
  0x80005f9: HAL_PWR_EnableBkUpAccess
  0x8000609: HAL_PWREx_GetVoltageRange
  0x800062d: HAL_PWREx_ControlVoltageScaling
  0x80006e5: HAL_PWREx_EnableVddIO2
  0x80006f5: RCC_SetFlashLatencyFromMSIRange
  0x8000771: HAL_RCC_GetSysClockFreq
  0x800080d: HAL_RCC_OscConfig
  0x8000d69: HAL_RCC_ClockConfig
  0x8000f5d: HAL_RCC_GetPCLK1Freq
  0x8000f81: HAL_RCC_GetPCLK2Freq
  0x8000fa5: RCCEx_PLLSAI1_Config
  0x80010ad: RCCEx_PLLSAI2_Config.constprop.0
  0x8001179: HAL_RCCEx_PeriphCLKConfig
  0x80015a5: HAL_RCCEx_EnableMSIPLLMode
  0x80015b5: HAL_TIM_PWM_PulseFinishedCallback
  0x80015b7: HAL_TIM_TriggerCallback
  0x80015b9: HAL_TIM_IRQHandler
  0x8001719: TIM_Base_SetConfig
  0x80017e5: HAL_TIM_Base_Init
  0x8001845: HAL_TIMEx_CommutCallback
  0x8001847: HAL_TIMEx_BreakCallback
  0x8001849: HAL_TIMEx_Break2Callback
  0x800184d: UART_EndRxTransfer
  0x80018a5: UART_TxISR_16BIT.part.0
  0x80018cb: UART_TxISR_8BIT
  0x80018fb: UART_TxISR_16BIT
  0x800192f: UART_TxISR_16BIT_FIFOEN.part.0
  0x800195b: UART_TxISR_8BIT_FIFOEN
  0x80019a5: UART_TxISR_16BIT_FIFOEN
  0x80019f3: HAL_UART_MspInit
  0x80019f5: HAL_UART_Transmit_IT
  0x8001abd: UART_DMAAbortOnError
  0x8001ad1: HAL_UARTEx_RxEventCallback
  0x8001ad5: HAL_UART_IRQHandler
  0x8001dbd: UART_RxISR_16BIT.part.0
  0x8001e25: UART_RxISR_16BIT
  0x8001e63: UART_RxISR_8BIT
  0x8001ead: UART_RxISR_8BIT_FIFOEN
  0x8002029: UART_RxISR_16BIT_FIFOEN
  0x80021a1: HAL_HalfDuplex_EnableTransmitter
  0x80021ed: HAL_HalfDuplex_EnableReceiver
  0x8002239: HAL_UART_GetState
  0x8002245: UART_SetConfig
  0x8002511: UART_AdvFeatureConfig
  0x80025b9: UART_WaitOnFlagUntilTimeout
  0x800267d: UART_CheckIdleState
  0x80026e7: HAL_UART_Init
  0x8002747: HAL_HalfDuplex_Init
  0x80027b1: UART_Start_Receive_IT
  0x80028d5: HAL_UART_Receive_IT
  0x8002929: HAL_UARTEx_RxFifoFullCallback
  0x800292b: HAL_UARTEx_TxFifoEmptyCallback
  0x800292d: HAL_UARTEx_EnableStopMode
  0x8002959: HAL_UARTEx_DisableStopMode
  0x8002985: set_GPIO_Port_Clock
  0x8002aa5: HAL_DAC_MspDeInit
  0x8002ad1: dac_stop
  0x8002b09: pwm_stop
  0x8002b69: getCurrentMillis
  0x8002b6d: osSystickHandler
  0x8002b6f: SysTick_Handler
  0x8002b81: enableClock
  0x8002c21: configHSECapacitorTuning
  0x8002c25: configIPClock
  0x8002c55: dwt_init
  0x8002c8d: hw_config_init
  0x8002ca7: _ZNSt14_Function_baseD1Ev
  0x8002cb9: HAL_GPIO_EXTI_Callback
  0x8002ce5: EXTI0_IRQHandler
  0x8002ceb: EXTI1_IRQHandler
  0x8002cf1: EXTI2_IRQHandler
  0x8002cf7: EXTI3_IRQHandler
  0x8002cfd: EXTI4_IRQHandler
  0x8002d03: EXTI9_5_IRQHandler
  0x8002d19: EXTI15_10_IRQHandler
  0x8002d31: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8002db9: _GLOBAL__sub_D__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8002dd5: LL_GPIO_SetPinPull
  0x8002dff: pin_in_pinmap
  0x8002e1d: pin_function
  0x8002f49: pinmap_pinout
  0x8002f71: pinmap_find_peripheral
  0x8002f87: pinmap_peripheral
  0x8002f93: pinmap_find_pin
  0x8002fa9: pinmap_pin
  0x8002fb5: pinmap_find_function
  0x8002fcb: pinmap_function
  0x8002fd5: pinmap_merge_peripheral
  0x8002fe7: _Error_Handler
  0x8002fe9: SystemInit
  0x800302d: get_timer_obj
  0x8003031: enableTimerClock
  0x8003191: disableTimerClock
  0x8003279: getTimerUpIrq
  0x800331d: getTimerCCIrq
  0x80033c5: HAL_TIM_Base_MspInit
  0x8003415: uart_init.part.0
  0x80036fd: uart_init
  0x8003705: serial_rx_active
  0x8003729: serial_tx_active
  0x800374d: uart_getc
  0x8003785: uart_attach_rx_callback
  0x80037c5: uart_attach_tx_callback
  0x8003809: uart_enable_tx
  0x8003829: uart_enable_rx
  0x8003849: HAL_UART_RxCpltCallback
  0x8003851: HAL_UART_TxCpltCallback
  0x8003859: HAL_UART_ErrorCallback
  0x80038a1: USART1_IRQHandler
  0x80038b9: USART2_IRQHandler
  0x80038d5: USART3_IRQHandler
  0x80038f1: UART4_IRQHandler
  0x8003909: UART5_IRQHandler
  0x8003921: LPUART1_IRQHandler
  0x8003939: HAL_UARTEx_WakeupCallback
  0x8003945: _sbrk
  0x8003981: _exit
  0x8003985: _kill
  0x8003995: _getpid
  0x8003999: setup
  0x80039e9: _Z17serial_read_bytesPcj
  0x8003a11: _Z12process_dataPcj
  0x8003a5d: loop
  0x8003ac5: _ZN14HardwareSerial9availableEv
  0x8003ad5: _ZN14HardwareSerial4peekEv
  0x8003aef: _ZN14HardwareSerial17availableForWriteEv
  0x8003b0b: _ZN14HardwareSerial5writeEh
  0x8003b23: _ZN14HardwareSerial16_rx_complete_irqEP8serial_s
  0x8003b5d: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x8003bc5: _ZN14HardwareSerial5writeEPKhj
  0x8003ca9: _ZN14HardwareSerial5flushEv
  0x8003cbd: _ZN14HardwareSerial4initE7PinNameS0_
  0x8003ce5: _ZN14HardwareSerial5setRxEm
  0x8003d2d: _ZN14HardwareSerial5setTxEm
  0x8003d75: _ZN14HardwareSerialC1EPv16HalfDuplexMode_t
  0x8003de9: _ZN14HardwareSerial18enableHalfDuplexRxEv
  0x8003e15: _ZN14HardwareSerial5beginEmh
  0x8003eb9: _ZN14HardwareSerial4readEv
  0x8003ee9: _GLOBAL__sub_I_Serial1
  0x8003efd: _ZNSt8functionIFvvEEaSEDn.isra.0
  0x8003f15: _Z15get_timer_indexP11TIM_TypeDef
  0x8003fa9: _ZN13HardwareTimerD1Ev
  0x8003fe9: _ZN13HardwareTimer5setupEP11TIM_TypeDef
  0x80040a1: _ZN13HardwareTimerC2EP11TIM_TypeDef
  0x80040c1: TIM1_UP_TIM16_IRQHandler
  0x80040e5: TIM1_CC_IRQHandler
  0x80040f9: TIM2_IRQHandler
  0x800410d: TIM3_IRQHandler
  0x8004121: TIM4_IRQHandler
  0x8004135: TIM5_IRQHandler
  0x8004149: TIM6_DAC_IRQHandler
  0x800415d: TIM7_IRQHandler
  0x8004171: TIM8_UP_IRQHandler
  0x8004185: TIM8_CC_IRQHandler
  0x8004189: TIM1_BRK_TIM15_IRQHandler
  0x800419d: TIM1_TRG_COM_TIM17_IRQHandler
  0x80041b1: _ZNKSt8functionIFvvEEclEv
  0x80041c5: _ZN13HardwareTimer14updateCallbackEP17TIM_HandleTypeDef
  0x80041ed: HAL_TIM_PeriodElapsedCallback
  0x80041f1: _ZN13HardwareTimer22captureCompareCallbackEP17TIM_HandleTypeDef
  0x8004241: HAL_TIM_OC_DelayElapsedCallback
  0x8004245: HAL_TIM_IC_CaptureCallback
  0x8004249: _ZN6Stream9timedReadEv
  0x8004273: _ZN6Stream9readBytesEPcj
  0x8004295: _ZN6Stream14readBytesUntilEcPcj
  0x80042c5: _Z7premainv
  0x80042d5: main
  0x80042e9: _Znwj
  0x80042ed: _ZdlPvj
  0x80042f1: Reset_Handler
  0x8004302: CopyDataInit
  0x8004308: LoopCopyDataInit
  0x8004316: FillZerobss
  0x800431a: LoopFillZerobss
  0x8004326: LoopForever
  0x8004340: Default_Handler
  0x8004341: DMA2_Channel3_IRQHandler
  0x8004345: pinMode
  0x8004425: digitalWrite
  0x8004499: millis
  0x800449d: delay
  0x80044b9: _Z14serialEventRunv
  0x80044d5: init
  0x80044d9: yield
  0x80044dd: __udivmoddi4
  0x80047a1: _ZSt25__throw_bad_function_callv
  0x80047a7: abort
  0x80047b5: calloc
  0x80047c5: __libc_init_array
  0x800480d: malloc
  0x800481d: free
  0x800482d: memcpy
  0x8004849: memset
  0x8004859: _calloc_r
  0x8004879: _free_r
  0x8004919: _malloc_r
  0x80049cd: _sbrk_r
  0x80049ed: _raise_r
  0x8004a3d: raise
  0x8004a4d: _kill_r
  0x8004a71: _getpid_r
  0x8004a75: __retarget_lock_acquire_recursive
  0x8004a77: __retarget_lock_release_recursive
  0x8004a79: __malloc_lock
  0x8004a85: __malloc_unlock
  0x8004a90: __EH_FRAME_BEGIN__
  0x8004a91: _init
  0x8004a9d: _fini
  0x8004aa8: PinMap_DAC
  0x8004acc: PinMap_TIM
  0x8004c7c: PinMap_UART_RX
  0x8004d00: PinMap_UART_TX
  0x8004e08: analogInputPin
  0x8004e48: digitalPin
  0x8004f94: CSWTCH.60
  0x8004f97: CSWTCH.61
  0x8004fa4: UARTPrescTable
  0x8005084: pin_map_ll
  0x80050c4: AHBPrescTable
  0x80050d4: APBPrescTable
  0x80050dc: MSIRangeTable
  0x8005181: CSWTCH.49
  0x8005188: CSWTCH.50
  0x8005194: _ZTV14HardwareSerial
  0x8005278: __sf_fake_stderr
  0x8005298: __sf_fake_stdin
  0x80052b8: __sf_fake_stdout
  0x80052d8: __exidx_start
  0x80052e0: __exidx_end
  0x80052e4: __frame_dummy_init_array_entry
  0x80052f0: __init_array_end
  0x80052f8: _sidata
  0x20000000: _sdata
  0x20000004: uwTickPrio
  0x20000008: GPIOPort
  0x2000002c: SystemCoreClock
  0x20000030: heap_end.11120
  0x20000034: _impure_ptr
  0x20000038: impure_data
  0x20000098: _edata
  0x2000009c: object.10279
  0x200000b4: _ZL13gpio_irq_conf
  0x200001f4: uart_handlers
  0x2000020c: buf
  0x20000210: led_state
  0x20000214: Serial1
  0x2000036c: HardwareTimer_Handle
  0x20000398: g_anOutputPinConfigured
  0x200003bc: __malloc_free_list
  0x200003c0: __malloc_sbrk_start
  0x200003c4: uwTick
  0x200003c8: errno
  0x200003cc: __lock___atexit_recursive_mutex
  0x200003cd: __lock___arc4random_mutex
  0x200003ce: __lock___env_recursive_mutex
  0x200003cf: __lock___sinit_recursive_mutex
  0x200003d0: __lock___malloc_recursive_mutex
  0x200003d1: __lock___at_quick_exit_mutex
  0x200003d2: __lock___dd_hash_mutex
  0x200003d3: __lock___tz_mutex
  0x200003d4: __lock___sfp_recursive_mutex
  0x200003d8: _end
  0x200a0000: _estack
  0xf1e0f85f: BootRAM
