interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x08000000
    permissions: rw-
    size: 0x48000
  text:
    base_addr: 0x10000000
    file: mtb-example-anycloud-wifi-web-server.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x100000
